"""make ip (IpAddress) unique field

Revision ID: 097902166c4f
Revises: dd63e433d17a
Create Date: 2024-08-18 20:40:26.969871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097902166c4f'
down_revision: Union[str, None] = 'dd63e433d17a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ip_addresses_ip', table_name='ip_addresses')
    op.create_index(op.f('ix_ip_addresses_ip'), 'ip_addresses', ['ip'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ip_addresses_ip'), table_name='ip_addresses')
    op.create_index('ix_ip_addresses_ip', 'ip_addresses', ['ip'], unique=False)
    # ### end Alembic commands ###
