"""Add visited_at (datetime) field in IpAddress

Revision ID: 273de06ac771
Revises: dcdd950dbb31
Create Date: 2024-08-18 17:39:11.977802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273de06ac771'
down_revision: Union[str, None] = 'dcdd950dbb31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_addresses', sa.Column('visited_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ip_addresses', 'visited_at')
    # ### end Alembic commands ###
