"""Choice field starts from lowercase letter (wallet_network)

Revision ID: 2bd4e7e69625
Revises: 99a45a18aa9c
Create Date: 2024-08-22 18:41:42.067663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd4e7e69625'
down_revision: Union[str, None] = '99a45a18aa9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
