"""add rang_id field

Revision ID: 38d31c385aaa
Revises: f3f122a6b6ec
Create Date: 2024-08-30 14:20:02.838505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d31c385aaa'
down_revision: Union[str, None] = 'f3f122a6b6ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rang_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rang_id')
    # ### end Alembic commands ###
