"""change default func.now() to datetime.now

Revision ID: 3dcbda3b1426
Revises: e4d95e2df049
Create Date: 2024-08-28 16:39:01.380975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dcbda3b1426'
down_revision: Union[str, None] = 'e4d95e2df049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
