"""change rang_id field name

Revision ID: 8fea5ec9bd36
Revises: 38d31c385aaa
Create Date: 2024-09-08 21:55:06.324351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fea5ec9bd36'
down_revision: Union[str, None] = '38d31c385aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rank_id', sa.Integer(), nullable=True))
    op.drop_column('users', 'rang_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rang_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'rank_id')
    # ### end Alembic commands ###
