"""delete task_count field

Revision ID: 9dd3aee8e369
Revises: 3dcbda3b1426
Create Date: 2024-08-29 20:51:16.748643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd3aee8e369'
down_revision: Union[str, None] = '3dcbda3b1426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quests', 'task_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('task_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
