"""indexing visited_at field

Revision ID: a28d10f0340a
Revises: 097902166c4f
Create Date: 2024-08-19 21:25:50.384173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a28d10f0340a'
down_revision: Union[str, None] = '097902166c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ip_addresses_visited_at'), 'ip_addresses', ['visited_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ip_addresses_visited_at'), table_name='ip_addresses')
    # ### end Alembic commands ###
