"""change experience fields with xp

Revision ID: f3f122a6b6ec
Revises: 9dd3aee8e369
Create Date: 2024-08-29 21:14:39.826937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f122a6b6ec'
down_revision: Union[str, None] = '9dd3aee8e369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('xp', sa.Integer(), nullable=True))
    op.drop_column('quests', 'reward_exp')
    op.add_column('users', sa.Column('xp', sa.Integer(), nullable=True))
    op.drop_column('users', 'experience')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('experience', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'xp')
    op.add_column('quests', sa.Column('reward_exp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('quests', 'xp')
    # ### end Alembic commands ###
